### ISSUE TITLE
Caught ticking entity

### ISSUE THREAD

**Issue by b0nkers96** [seymourimadeit/Piglin-Proliferation#31]
java.lang.IllegalArgumentException: No implementation of the random number generator algorithm "L32X64MixRandom" is available
	at java.base/java.util.random.RandomGeneratorFactory.findProvider(Unknown Source)
	at java.base/java.util.random.RandomGeneratorFactory.of(Unknown Source)
	at java.base/java.util.random.RandomGenerator.of(Unknown Source)
	at java.base/java.util.random.RandomGenerator.getDefault(Unknown Source)
	at TRANSFORMER/piglinproliferation@2.0.7/tallestred.piglinproliferation.common.attribute.RangedRandomAttributeModifierHolder$Instance.random(RangedRandomAttributeModifierHolder.java:120)
	at TRANSFORMER/piglinproliferation@2.0.7/tallestred.piglinproliferation.common.attribute.RangedRandomAttributeModifierHolder$Instance.randomIntAmount(RangedRandomAttributeModifierHolder.java:115)
	at TRANSFORMER/piglinproliferation@2.0.7/tallestred.piglinproliferation.common.items.BucklerItem.bucklerBash(BucklerItem.java:122)
	at TRANSFORMER/piglinproliferation@2.0.7/tallestred.piglinproliferation.PPEvents.onLivingTick(PPEvents.java:151)
	at MC-BOOTSTRAP/net.neoforged.bus/net.neoforged.bus.SubscribeEventListener.invoke(SubscribeEventListener.java:49)
	at MC-BOOTSTRAP/net.neoforged.bus/net.neoforged.bus.EventBus.post(EventBus.java:350)
	at MC-BOOTSTRAP/net.neoforged.bus/net.neoforged.bus.EventBus.post(EventBus.java:315)
	at TRANSFORMER/neoforge@21.1.55/net.neoforged.neoforge.event.EventHooks.fireEntityTickPre(EventHooks.java:935)
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:773)
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.level.Level.mixinextras$bridge$accept$173(Level.java)
	at TRANSFORMER/neruina@2.1.2/com.bawnorton.neruina.handler.TickHandler.safelyTickEntities(TickHandler.java:92)
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.level.Level.wrapOperation$bae000$neruina$catchTickingEntities$notTheCauseOfTickLag(Level.java:6318)
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.level.Level.guardEntityTick(Level.java:570)
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.level.ServerLevel.lambda$tick$2(ServerLevel.java:420)
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:54)
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:400)
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1037)
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:317)
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:917)
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:707)
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:267)
	at java.base/java.lang.Thread.run(Unknown Source)

**Comment by seymourimadeit** [comment]
Could you please send the full log? I cannot seem to recreate this issue with just Piglin Proliferation and Neurina installed.

This also might be a problem with your java version being misinstalled, as seen by here: https://github.com/adoptium/temurin-build/issues/2843.

**Comment by seymourimadeit** [comment]
Could you please send the full log? I cannot seem to recreate this issue with just Piglin Proliferation and Neurina installed.

This also might be a problem with your java version being, though I only encountered previous issues of this being a cause via a quick google issues. I'd still try to find a way to reinstall your launcher's java if this is the case.

**Comment by b0nkers96** [comment]
[Uploading crash-2024-09-18_23.49.17-server.txt…]()

**Comment by b0nkers96** [comment]
[crash-2024-09-18_23.49.17-server.txt](https://github.com/user-attachments/files/17055387/crash-2024-09-18_23.49.17-server.txt)
